title: Brian Villegas Villalpando
description: PhD Student in Mathematics
theme: minima
updated: 2026-09-06

header_pages:
- index.md
- CV.md
- research.md
- teaching.md

favicon: /assets/img/favicon.png
