title: Brian Villegas Villalpando
description: PhD Student in Mathematics
theme: minima

header_pages:
- index.md
- CV.md
- research.md
- teaching.md

favicon: /assets/img/favicon.png

.home-layout {
    display: flex;
    gap: 50px;
    align-items: flex-start;
}

.home-text {
    flex: 1;
}

.home-photo img {
    width: 300px;
    border-radius: 8px;
}
